spring.application.name=ed-idp
server.port=9000

app.issuer-uri=http://localhost:9000
app.token.access-token-time-to-live=5m
app.token.refresh-token-time-to-live=7d
app.token.reuse-refresh-tokens=false
app.token.client-credentials-allowed-scopes=read,write,introspection,revocation

spring.datasource.url=jdbc:h2:mem:authdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

tenant.resolution.header-enabled=true
tenant.resolution.path-enabled=true
tenant.resolution.header-name=X-Tenant-ID
tenant.resolution.enforce-trusted-proxy-for-header=false
tenant.resolution.header-trusted-sources=127.0.0.1,::1,0:0:0:0:0:0:0:1
tenant.resolution.require-explicit-tenant=false

spring.jpa.open-in-view=false
